### PR TITLE
#20 fix GHA workflow

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #20

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse in original Travis configuration, we tested different rnp versions only against ruby 2.5. some questions regarding this:
 - do we still need it?
 - should we test it on other ruby versions too?

**Comment by ribose-jeffreylau** [comment]
@CAMOBAP I think we can test against Ruby 2.6, 2.7 and possibly 3.0, since 2.5.9 is EOL'd.

As for macos and Windows, they're nice-to-have targets but not a high priority, since tests on those platforms in https://github.com/rnpgp/ruby-rnp should ideally give us enough confidence that they'd also work when Linux works.

**Comment by CAMOBAP** [comment]
@ronaldtse the workflow by itself work, after several fixes I ended up with 

```
ArgumentError: wrong number of arguments (given 0, expected 1)
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/bundler/gems/activeuuid-8d8accd7017c/lib/activeuuid/patches.rb:175:in `initialize_type_map'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:526:in `reload_type_map'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:166:in `clear_cache!'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:394:in `disconnect!'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:103:in `disconnect!'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:455:in `block (3 levels) in disconnect'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:450:in `each'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:450:in `block (2 levels) in disconnect'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:449:in `block in disconnect'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:697:in `block in with_exclusively_acquired_all_connections'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:772:in `with_new_connections_blocked'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:695:in `with_exclusively_acquired_all_connections'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `disconnect'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:470:in `disconnect!'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:1050:in `remove_connection'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:977:in `establish_connection'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_handling.rb:60:in `establish_connection'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/bundler/gems/activeuuid-8d8accd7017c/lib/activeuuid/patches.rb:190:in `establish_connection'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/tasks/sqlite_database_tasks.rb:6:in `establish_connection'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/tasks/sqlite_database_tasks.rb:15:in `create'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/tasks/sqlite_database_tasks.rb:33:in `purge'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:209:in `purge'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/railties/databases.rake:339:in `block (3 levels) in <top (required)>'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/railties/databases.rake:345:in `block (3 levels) in <top (required)>'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.6.8/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/2.6.8/x64/bin/bundle:23:in `<main>'
Tasks: TOP => app:db:test:load => app:db:test:purge
(See full trace by running task with --trace)
Error: Process completed with exit code 1.
```

I need someones help to troubleshoot this and propose to merger this PR, I'm switching to IETF

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP , let's merge this first and we'll post a new issue to fix the error.

**Pull request merged**
