### PR TITLE
#20 move to GHA

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #20

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse may I ask for write access to the original repo. This workflow isn't usually so I may need to modify it often (first time) to make it work

**Comment by ronaldtse** [comment]
@CAMOBAP you have full access now. Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP you have full access now. Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP we should update RNP here to v15.

**Pull request merged**
